image: node:12
clone:
  depth: full
pipelines:
  default:
      - step:
          script:
            - npm install
            - npm test
  custom:
    migration:
      - step:
          script:
            - npm run migration:run
            - npm test
  branches:
    development:
      - step:
          name: Deploy to staging
          deployment: staging
          caches:
            - node
          script:
            - npm install
            - npm test
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING_APP_NAME.git master